site_name: "MatTech Lab SOPS"
site_description: standard operating procedures (SOPs) of MatTech Lab
site_author: MatTech Members
site_url: https://mattechlab.github.io/SOPS/

# Copyright
copyright: Copyright &copy; 2023


nav:
    - Home: index.md
    - General experimental procedures:
      - Recruitment, scheduling, and screening:
        - Recruitment and screening: general/recruit-schedule-screen/participants-recruitment.md
        - Scheduling: general/recruit-schedule-screen/scanner-scheduling.md
      - Data management:
        - Data export: general/data-management/1_data_export.md
        - EDF-to-BIDS conversion: general/data-management/2_et1_edf_to_bids.md
        - Standard data storage: general/data-management/3_data_storage.md
      - Eye Tracking-related procedures:
        - ET software installation (Eyelink): general/et-related/et_software_install.md
        - General ET guideline: general/et-related/general-et-notes.md
    - Debi protocol:
      - Data collection: debi/data-collection/data-collection_DEBI_protocol.md
      - Data processing:
        - Overall data workflow: debi/data-processing/0_overall-data-workflow.md
        - ET processing in MR-Eye 2.0: debi/data-processing/1_1_et_QAQC_of_mreye_data.md
        - ET processing in MREye_Track: debi/data-processing/1_2_et_QAQC_of_mreye_tracking.md
        - MRI data processing: debi/data-processing/2_MRI_post_processing.md
    - HiFi protocols:
      - Visual checkerboard fMRI protocol: 
        - Data collection: hifi/visual/data-collection_visuo.md
      - Audio fMRI protocol: 
        - Data collection: hifi/audio/data-collection_audio.md
      - Resting state fMRI protocol: 
        - Data collection: hifi/resting/data-collection_rs.md


theme:
  name: material
  palette:
    primary: black
  logo: assets/images/Logo_squared_v1.svg
  features:
    # - tabs
    - navigation.instant
    # - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
  icon:
    admonition:
      thanks: octicons/code-of-conduct-16
      quote: fontawesome/solid/comment-dots
      danger: fontawesome/solid/circle-exclamation
      warning: fontawesome/solid/traffic-light
      important: fontawesome/solid/bullhorn
      tip: fontawesome/solid/bookmark
      bug: fontawesome/regular/circle-xmark


plugins:
  - search
  - macros:
      include_dir: include
      include_yaml:
        - secrets: 'include/secrets.yml'
        - settings: 'include/study-settings.yml'
      on_undefined: lax
  - mkdocs-jupyter:
      ignore:
        - "*.py"
        - "assets/code/physioconv/.ipynb_checkpoints/physio-to-bids-checkpoint.ipynb"
        - "assets/code/physioconv/physio-to-bids.ipynb"
  # - mkpdfs:
  #     company: Lausanne University Hospital (CHUV)
  #     author: The Axon Lab
  #     toc_title: Table of Contents
  #     design: design/report.css
  #     output_path: pdf/documentation.pdf

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - include/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
