name: Run tests

on: [push]

jobs:  
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Files (Debug Step)
        run: ls -la
        
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          args: "--ignore-words=codespell_ignore.txt"
